name: Download CISA KEV json

on:
  schedule:
    - cron: '37 13 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  download-kev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download KEV JSON and capture Last-Modified
        run: |
          curl -sSL --compressed \
            -A "CISA-KEV-GitHubBot (+https://github.com/${{ github.repository }})" \
            -D headers.txt \
            -o known_exploited_vulnerabilities.json \
            https://www.cisa.gov/sites/default/files/feeds/known_exploited_vulnerabilities.json

          last_modified=$(grep -i ^Last-Modified headers.txt | cut -d' ' -f2-)
          echo "last_modified=$last_modified" >> $GITHUB_ENV

      - name: Validate JSON
        run: jq empty known_exploited_vulnerabilities.json

      - name: Commit if changed
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@users.noreply.github.com"
          git add known_exploited_vulnerabilities.json
          if ! git diff --cached --quiet; then
            git commit -m "Update KEV feed (Last-Modified: $last_modified)"
            git push origin HEAD:main
          else
            echo "No changes to commit."
          fi
